#!/bin/bash

BASE_DIR="/nfs/turbo/umd-anglial/GenImageDetector/raw_dataset_zip"
mkdir -p "$BASE_DIR"
cd "$BASE_DIR" || exit

MID_DIR="$BASE_DIR/midjourney"
mkdir -p "$MID_DIR"
cd "$MID_DIR" || exit

links=(
  "https://drive.google.com/file/d/1T-Ct8FO8c8wegw_c3WWsr1R-a2peFsVk/view?usp=drive_link"
  "https://drive.google.com/file/d/1o_GSkPUumdO43ccMVQguZJXJfM8o8Zul/view?usp=drive_link"
  "https://drive.google.com/file/d/1Jq3_cRF2L-6qu7IEBSTX1FRAi5UKFX7r/view?usp=drive_link"
  "https://drive.google.com/file/d/19_xCjljunYeOoXPkyj86K61bfguoDt0C/view?usp=drive_link"
  "https://drive.google.com/file/d/1Ci515Afi9w_n2nJr4zHK7rz8m8cDAh_O/view?usp=drive_link"
  "https://drive.google.com/file/d/1I_R2KzktE2-SCd--Rpxe5o3FDTV682Ba/view?usp=drive_link"
  "https://drive.google.com/file/d/1UmWYs4OKhJ9xX4s2EEDhGGevwl7tnDhp/view?usp=drive_link"
  "https://drive.google.com/file/d/1kD5PJasmzJ_pXBeF-2ZxvMTR6tL1hFZ7/view?usp=drive_link"
  "https://drive.google.com/file/d/10_drWBz9ZREwIQku2g7eCdMoX3N1FLcM/view?usp=drive_link"
  "https://drive.google.com/file/d/1JV0dKJmpD9iXfF53vwpotaaVtBpjV8HH/view?usp=drive_link"
  "https://drive.google.com/file/d/13KqxLbeJtyQ1Lu-Ey4vFBDnvS4HTYawd/view?usp=drive_link"
  "https://drive.google.com/file/d/1vjz2VdROW0LnmN-0CkQtq6lQHGF9ja0R/view?usp=drive_link"
  "https://drive.google.com/file/d/1IaMEEb7fKiTUcDhDJj30h9HVDbQO3eCF/view?usp=drive_link"
  "https://drive.google.com/file/d/1XReothTuIWQABLoVBP1xWRS0ri3FF7RV/view?usp=drive_link"
  "https://drive.google.com/file/d/19pFBoMFLtute8u9npf879xSn5GQBJ0oV/view?usp=drive_link"
  "https://drive.google.com/file/d/1q3yLUBPFE6YZJ03yojLuRys9tAZMhZGc/view?usp=drive_link"
  "https://drive.google.com/file/d/1kRSFPk7RRIzTOcmUXwybNBUCMtDNVv4f/view?usp=drive_link"
  "https://drive.google.com/file/d/1CBtiCid4V-IE3-jy24fQwWuoiQTPSojl/view?usp=drive_link"
  "https://drive.google.com/file/d/1w6fAKWHxt158JW58vbFKhkH3HLCybotu/view?usp=drive_link"
  "https://drive.google.com/file/d/1sMjka-vPUhtUZxndu0IKo8Rj4gwT40tz/view?usp=drive_link"
  "https://drive.google.com/file/d/1KzxCbSWwoVXU-1BLcKJ_wpfLjSis7Big/view?usp=drive_link"
  "https://drive.google.com/file/d/13t_Qgyjy822bt5fkpVNlmgS4Wrm1DolQ/view?usp=drive_link"
  "https://drive.google.com/file/d/1snc8-VZrMJBhUTvRvB4odTRtje8ib2za/view?usp=drive_link"
  "https://drive.google.com/file/d/1sMXG0kwRIjv2tmMzAjCcNgTDftctOXpn/view?usp=drive_link"
  "https://drive.google.com/file/d/1Zu796-1t1qzdcZ3sk2Cdl2Un0WizTq9N/view?usp=drive_link"
  "https://drive.google.com/file/d/1UXiqPcBtxnJ0qz7TsCWsqhFxUdzN9qmC/view?usp=drive_link"
  "https://drive.google.com/file/d/14g4fW5u4FTNg0QJyR6TMpAII_x8zB2B-/view?usp=drive_link"
  "https://drive.google.com/file/d/1TQRTFJ9W9vQodGroTOO8jdjG-KCdiHmY/view?usp=drive_link"
  "https://drive.google.com/file/d/1qxcWKNdMgwwGmwGj0qtgtBvNOV8VGCnk/view?usp=drive_link"
  "https://drive.google.com/file/d/16VaK0e9bPbMBiY59iX14KDRtummoSlPl/view?usp=drive_link"
  "https://drive.google.com/file/d/1m3uoTUogypcr9aGc120MFxdtXfwgwJcJ/view?usp=drive_link"
  "https://drive.google.com/file/d/1SbWMBZKKNRU31CDECfEPnCzQSuR8dPMl/view?usp=drive_link"
  "https://drive.google.com/file/d/1lL1MHZoM8yBer2zI389FvEhM3WVHPv7h/view?usp=drive_link"
  "https://drive.google.com/file/d/1_Pggy6tyAA0ZfZEBfXUhTP1rVwncpA11/view?usp=drive_link"
  "https://drive.google.com/file/d/1p6bVOkBqFdSRwxKU7azGVo4BO9QYr0kD/view?usp=drive_link"
  "https://drive.google.com/file/d/1c1H715wNk5ER7H02gruUOt6AL8sf91zi/view?usp=drive_link"
  "https://drive.google.com/file/d/1HgITWPo4WAQ8k_vK_70S4ZGmf4_c7ZaN/view?usp=drive_link"
  "https://drive.google.com/file/d/1ciz7KJ3jdGGbgrYu5EykcK7zkUgKou5A/view?usp=drive_link"
  "https://drive.google.com/file/d/1emQJaP-9Fo0or6X46Yky3Vel1GDvpAxZ/view?usp=drive_link"
  "https://drive.google.com/file/d/1-KeYmtYtRYmBkz9YsU2WCqqKktegWtJ1/view?usp=drive_link"
  "https://drive.google.com/file/d/1JPgLqFLeGivIZD5FSBBwtTRyByo1csIf/view?usp=drive_link"
  "https://drive.google.com/file/d/1AhwYY3JSeeZppxjnroJmTWF2enfCHZ1a/view?usp=drive_link"
  "https://drive.google.com/file/d/1pMjV_wylMlizpca2-5H6ZdUDQCTsrIgI/view?usp=drive_link"
  "https://drive.google.com/file/d/1odMqM4WRl4vEgBgjjFIqxa1zPtZEqF1G/view?usp=drive_link"
  "https://drive.google.com/file/d/1ihV49jxtbh_6f8XCIQ4Un5LNIBeuI1Hm/view?usp=drive_link"
  "https://drive.google.com/file/d/1Vm5URG7oodcYVklGn8Nm7kbuJMeSzNxl/view?usp=drive_link"
  "https://drive.google.com/file/d/1zDzZwzX5Qs4qLi_jGdF9Mx48pKrmbGL3/view?usp=drive_link"
  "https://drive.google.com/file/d/1gdwNZB0NR3uuNbR9OuytAiFJMc0mRnv2/view?usp=drive_link"
  "https://drive.google.com/file/d/154xscOrLsCkbQ4tzFyY8s6bhNqEid2D3/view?usp=drive_link"
  "https://drive.google.com/file/d/1dlckgE08uU6ID2pJM-LvF4kIacJZ-q0V/view?usp=drive_link"
  "https://drive.google.com/file/d/1YEVlrXlFLsc717Gy_OdSlFF3RiUQf97r/view?usp=drive_link"
  "https://drive.google.com/file/d/1F8N5ErMuWtHc4UsQrXFaQ5jvEABI9g7K/view?usp=drive_link"
  "https://drive.google.com/file/d/1_nJyBlblQ2RiTtmXk4wC0pBvwIXIIhDk/view?usp=drive_link"
  "https://drive.google.com/file/d/1KdS6RMRRaBHQYA98ST5wzyguRbtfTDD7/view?usp=drive_link"
  "https://drive.google.com/file/d/1E0zyqd1FmAAe2w-CjDetqKBsLgDvew9v/view?usp=drive_link"
  "https://drive.google.com/file/d/1rInzewHynoGp25x8T6WrmVYTebKct85c/view?usp=drive_link"
  "https://drive.google.com/file/d/1pSeeb9mON3A5aDBUuZa_JeEE59sliNOY/view?usp=drive_link"
  "https://drive.google.com/file/d/1XWQnC8L7BrjYFYmsCFa1MrGesvwyorsv/view?usp=drive_link"
  "https://drive.google.com/file/d/12sAdnodd7OjgsHAGmNd2-KCJubbxf6bp/view?usp=drive_link"
  "https://drive.google.com/file/d/131X_fvUwPBUDUp-wkDE9tE6Pqa-3cINY/view?usp=drive_link"
  "https://drive.google.com/file/d/1xQy7XCG8W3vXh0rgkxkFN2DyE1R10VsR/view?usp=drive_link"
  "https://drive.google.com/file/d/1mqYFXXOPBDu1KsARUS96kknpO7YSjMG6/view?usp=drive_link"
  "https://drive.google.com/file/d/1vQNJY2et8rhXxXlGGTyqhxxASsjXGcij/view?usp=drive_link"
  "https://drive.google.com/file/d/1ctoUCyTADMFbWGGCRvo6rzxsYn3LEvTD/view?usp=drive_link"
  "https://drive.google.com/file/d/1vbHHHrOGw6ZmQbi5ly61NnyUk4rAx-4C/view?usp=drive_link"
  "https://drive.google.com/file/d/1TJxvBQAc4-C-xKn_25VltdXsLmyMKnGH/view?usp=drive_link"
  "https://drive.google.com/file/d/1uI-pNbX1hM9snzFnsoQQgDOoMBm-BWWh/view?usp=drive_link"
  "https://drive.google.com/file/d/1kYauqFOm6SfOukU5P-6Xx39JGY7d1SxQ/view?usp=drive_link"
  "https://drive.google.com/file/d/1fJyhS-XY4UGd5YQ18mVLmIsmUTaZeEgD/view?usp=drive_link"
  "https://drive.google.com/file/d/1vmiMJA__1IzSSMrhk4uvqDNWgxrv1PuS/view?usp=drive_link"
  "https://drive.google.com/file/d/1sVDVgZoxSzgllYWC1Gzq3zjBV6fk7qN6/view?usp=drive_link"
)

echo "Downloading Midjourney dataset..."
for url in "${links[@]}"; do
  echo "Downloading from $url..."
  gdown --fuzzy "$url"
done

echo "All downloads complete!"
